"use client";

import React, { useEffect, useState } from "react";
import { getLearningPaths, LearningPathSchema } from "@/services/api";

/**
 * Displays the AI-generated Learning Paths page with a list of user's learning paths.
 * Fetches from the backend API and shows a clean, modern layout.
 */
export default function LearningPathPage() {
  // TODO: Replace this with actual user auth/id in real deployment.
  const [userId] = useState<string>("demo-user-001");
  const [paths, setPaths] = useState<LearningPathSchema[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    getLearningPaths(userId)
      .then(setPaths)
      .catch((err) => {
        setError(
          typeof err?.message === "string"
            ? err.message
            : "Could not load learning paths."
        );
      })
      .finally(() => setLoading(false));
  }, [userId]);

  return (
    <section className="max-w-3xl mx-auto p-6">
      <h1 className="text-3xl font-bold mb-3">🎓 Your AI Learning Paths</h1>
      <p className="text-gray-600 mb-7">
        These personalized learning journeys are generated by SkillBridge, tailored to your profile and goals.
      </p>

      {loading && (
        <div className="py-6 flex justify-center text-indigo-500 font-semibold">Loading...</div>
      )}

      {error && (
        <div className="bg-red-100 text-red-600 p-4 rounded mb-4">{error}</div>
      )}

      {!loading && !error && (
        <>
          {paths.length === 0 ? (
            <div className="bg-gray-50 border px-4 py-8 rounded text-gray-500 text-center">
              No learning paths found yet.<br />Get started by completing onboarding or requesting a new path.
            </div>
          ) : (
            <ul className="space-y-8">
              {paths.map((path) => (
                <li key={path.path_id} className="bg-white border border-gray-100 shadow-sm p-6 rounded">
                  <h2 className="font-semibold text-xl mb-1">{path.name}</h2>
                  <p className="text-sm text-gray-700 mb-4">{path.summary || "No summary provided."}</p>
                  <ol className="space-y-3 border-l-2 border-indigo-200 pl-4">
                    {path.items
                      .sort((a, b) => a.order - b.order)
                      .map((item) => (
                        <li
                          key={item.id}
                          className="relative pl-2 before:absolute before:-left-5 before:top-1.5 before:w-3 before:h-3 before:bg-indigo-400 before:rounded-full"
                        >
                          <div className="font-medium">{item.title}</div>
                          {item.description && (
                            <div className="text-xs text-gray-600">{item.description}</div>
                          )}
                          {item.resource_link && (
                            <a
                              href={item.resource_link}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="inline-block text-xs mt-1 text-indigo-600 underline hover:text-indigo-800"
                            >
                              Resource
                            </a>
                          )}
                        </li>
                      ))}
                  </ol>
                  <div className="mt-3 text-xs text-gray-400">
                    Created: {path.created_at ? new Date(path.created_at).toLocaleDateString() : "N/A"}
                  </div>
                </li>
              ))}
            </ul>
          )}
        </>
      )}
    </section>
  );
}
