"use client";

import React, { useEffect, useState } from "react";
import { getGenericProjectIdeas, ProjectIdeaSchema } from "@/services/api";

/**
 * Displays the AI-generated project ideas page.
 * Fetches generic project ideas and renders them in a modern, card-style layout.
 */
export default function ProjectsPage() {
  const [ideas, setIdeas] = useState<ProjectIdeaSchema[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    getGenericProjectIdeas()
      .then(setIdeas)
      .catch((err) => {
        setError(
          typeof err?.message === "string"
            ? err.message
            : "Could not load project ideas."
        );
      })
      .finally(() => setLoading(false));
  }, []);

  return (
    <section className="max-w-4xl mx-auto p-6">
      <h1 className="text-3xl font-bold mb-3">💡 Project Ideas</h1>
      <p className="text-gray-600 mb-7">
        Explore engaging project suggestions generated by SkillBridge AI—boost your skills with hands-on experience!
      </p>

      {loading && (
        <div className="py-6 flex justify-center text-indigo-500 font-semibold">Loading...</div>
      )}

      {error && (
        <div className="bg-red-100 text-red-600 p-4 rounded mb-4">{error}</div>
      )}

      {!loading && !error && (
        <>
          {ideas.length === 0 ? (
            <div className="bg-gray-50 border px-4 py-8 rounded text-gray-500 text-center">
              No project ideas available at the moment.<br />Try again later!
            </div>
          ) : (
            <div className="grid gap-7 sm:grid-cols-2">
              {ideas.map((idea) => (
                <div key={idea.idea_id} className="bg-white border border-gray-100 shadow p-5 rounded-lg flex flex-col">
                  <h2 className="font-semibold text-lg mb-1">{idea.title}</h2>
                  <div className="text-xs text-gray-500 mb-2">
                    {idea.difficulty && (
                      <span className="inline-block px-2 py-0.5 bg-blue-100 text-blue-600 rounded-full mr-2">
                        {idea.difficulty}
                      </span>
                    )}
                    {idea.tags && idea.tags.length > 0 && (
                      <span>
                        {idea.tags.map((tag) => (
                          <span
                            key={tag}
                            className="inline-block px-2 py-0.5 bg-gray-100 text-gray-600 rounded-full mr-1"
                          >
                            {tag}
                          </span>
                        ))}
                      </span>
                    )}
                  </div>
                  <p className="text-gray-700 text-sm flex-1">{idea.description}</p>
                  <div className="flex flex-wrap gap-2 mt-3">
                    {idea.technologies.map((tech) => (
                      <span
                        key={tech}
                        className="bg-indigo-50 text-indigo-800 text-xs px-2 py-0.5 rounded"
                      >
                        {tech}
                      </span>
                    ))}
                  </div>
                  <div className="mt-2 text-xs text-gray-400">
                    {idea.created_at ? <>Added {new Date(idea.created_at).toLocaleDateString()}</> : null}
                  </div>
                </div>
              ))}
            </div>
          )}
        </>
      )}
    </section>
  );
}
